/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MinesweeperImport } from './routes/minesweeper'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MinesweeperRoute = MinesweeperImport.update({
  id: '/minesweeper',
  path: '/minesweeper',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/minesweeper': {
      id: '/minesweeper'
      path: '/minesweeper'
      fullPath: '/minesweeper'
      preLoaderRoute: typeof MinesweeperImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/minesweeper': typeof MinesweeperRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/minesweeper': typeof MinesweeperRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/minesweeper': typeof MinesweeperRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/minesweeper'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/minesweeper'
  id: '__root__' | '/' | '/minesweeper'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MinesweeperRoute: typeof MinesweeperRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MinesweeperRoute: MinesweeperRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/minesweeper"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/minesweeper": {
      "filePath": "minesweeper.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
