/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MinesweeperImport } from './routes/minesweeper'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as NojsIndexImport } from './routes/nojs/index'

// Create/Update Routes

const MinesweeperRoute = MinesweeperImport.update({
  id: '/minesweeper',
  path: '/minesweeper',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NojsIndexRoute = NojsIndexImport.update({
  id: '/nojs/',
  path: '/nojs/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/minesweeper': {
      id: '/minesweeper'
      path: '/minesweeper'
      fullPath: '/minesweeper'
      preLoaderRoute: typeof MinesweeperImport
      parentRoute: typeof rootRoute
    }
    '/nojs/': {
      id: '/nojs/'
      path: '/nojs'
      fullPath: '/nojs'
      preLoaderRoute: typeof NojsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/minesweeper': typeof MinesweeperRoute
  '/nojs': typeof NojsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/minesweeper': typeof MinesweeperRoute
  '/nojs': typeof NojsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/minesweeper': typeof MinesweeperRoute
  '/nojs/': typeof NojsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/minesweeper' | '/nojs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/minesweeper' | '/nojs'
  id: '__root__' | '/' | '/about' | '/minesweeper' | '/nojs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MinesweeperRoute: typeof MinesweeperRoute
  NojsIndexRoute: typeof NojsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MinesweeperRoute: MinesweeperRoute,
  NojsIndexRoute: NojsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/minesweeper",
        "/nojs/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/minesweeper": {
      "filePath": "minesweeper.tsx"
    },
    "/nojs/": {
      "filePath": "nojs/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
